schema {
	query: Query
	mutation: Mutation
}

type Query {
	collection(id: ID!): Collection
	collections: [Collection!]!
}

type Mutation {
	createCollection(input: CreateCollectionInput!): CreateCollectionOutput
	deleteCollection(input: DeleteCollectionInput!): DeleteCollectionOutput
	clearDataResourceFromCollection(input: clearDataResourceFromCollectionInput!): clearDataResourceFromCollectionOutput
}

type Collection {
	id: ID!
}

input CreateCollectionInput {
	collectionId: ID!
}

type CreateCollectionOutput {
	collectionId: ID!

}

input DeleteCollectionInput {
	collectionId: ID!
}

type DeleteCollectionOutput {
	collectionId: ID!
}

input clearDataResourceFromCollectionInput {
	collectionId: ID!
	dataResourceId: ID!
}

type clearDataResourceFromCollectionOutput {
	collectionId: ID!
	dataResourceId: ID!
}