schema {
	query: Query
	mutation: Mutation
}

type Query {
	index(id: ID!): Index
	indices: [Index!]!

	activeIndex: Index
}

type Mutation {
	getOrCreateIndex(input: GetOrCreateIndexInput!): GetOrCreateIndexOutput!
	deleteIndex(input: DeleteIndexInput!): DeleteIndexOutput!
	clearDataResourceFromIndex(input: ClearDataResourceFromIndexInput!): ClearDataResourceFromIndexOutput!
	setActiveIndex(input: SetActiveIndexInput!): SetActiveIndexOutput!
}

type Index {
	id: ID!
}

input GetOrCreateIndexInput {
	indexId: ID!
}

type GetOrCreateIndexOutput {
	indexId: ID!

}

input DeleteIndexInput {
	indexId: ID!
}

type DeleteIndexOutput {
	indexId: ID!
}

input ClearDataResourceFromIndexInput {
	indexId: ID!
	dataResourceId: ID!
}

type ClearDataResourceFromIndexOutput {
	indexId: ID!
	dataResourceId: ID!
}

input SetActiveIndexInput {
	indexId: ID!
}

type SetActiveIndexOutput {
	indexId: ID!
}